DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS product;

CREATE TABLE client (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  address TEXT UNIQUE NOT NULL,
  e_mail TEXT UNIQUE NOT NULL,
  phone TEXT UNIQUE NOT NULL
);

CREATE TABLE product (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  price INTEGER NOT NULL,
  description TEXT NOT NULL
);

